language: java

jdk:
  - oraclejdk8
  - openjdk8

addons:
  apt:
    packages:
      - oracle-java8-installer 

os:
  - linux

addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
    organization: "hebelala-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
