language: java

jdk:
  - oraclejdk8
  - openjdk8

os:
  - linux
  - osx

addons:
  sonarcloud:
    organization: "hebelala-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
